[package]
name = "aa-client"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.0", features = ["full"] }
# reqwest = { version = "*", features = ["json", "rustls-tls"] }
# serde = { version = "*", features = ["derive"] }
# serde_json = "*"
