[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

# Network configurations
[rpc_endpoints]
anvil = "http://localhost:8545"
sepolia = "${ALCHEMY_HTTP_SEPOLIA}"

